# Generated by Django 2.0.6 on 2018-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20181014_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_grade',
            field=models.FloatField(default=65),
        ),
    ]
